[general]
email = "[theme]
base =

# Primary accent color for interactive elements.
primaryColor = "#FF9600"

# Background color for the main content area.
backgroundColor = "#16171A"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#050506"

# Color used for almost all text.
textColor = "#E8AAE7"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
font = "monospace" 
